name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  SAST_Check:
    name: Static Analysis (SAST)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Bandit (Python security scanner)
      uses: pypa/gh-action-pypi-bandit@v1.0.0
      with:
        targets: .

  SCA_Check:
    name: Dependency Vulnerability Scan (SCA)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Safety (Python SCA)
      uses: pyupio/safety-action@v1.0.0
      with:
        api-key: ${{ secrets.SAFETY_API_KEY }}
      continue-on-error: true

  DAST_Check:
    name: OWASP ZAP Baseline Scan (DAST)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Start Flask App
      run: |
        pip install -r requirements.txt
        nohup python app.py &
        sleep 5

    - name: Run ZAP Baseline Scan
      uses: zaproxy/action-baseline@v0.7.0
      with:
        target: 'http://127.0.0.1:5000'
